services:
  ohmycert:
    image: nyabase/ohmycert:latest
    restart: always
    command: daemon
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./config.json:/app/config/config.json
    environment:
      - TZ=Asia/Shanghai
